apiVersion: v1
kind: Pod
metadata:
  name: task-1
  namespace: mohan
spec:
  containers:
  - name: time-printer
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - while true; do date; sleep 60; done
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
