apiVersion: v1
kind: Pod
metadata:
  name: busybox-example
  namespace: mohan
spec:
  containers:
  - name: main-container
    image: busybox
    command: ['sh', '-c', 'echo "Main container started"; sleep 5; echo "Main container finished"']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'echo "Init container started"; sleep 10; echo "Init container finished"']
