apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-task-5
  namespace: mohan
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.16.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"